server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis 配置文件所在路径
  type-aliases-package: com.tws.entity                  #所有Entity别名类所在包
  mapper-location:
    -classpath: mybatis/mapper/**/*.xml                 #mapper映射文件

spring:
  appclication:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruiDataSource       #当前数据源操作类型
    driver-class-name: org.git.mm.msql.Driver         #MySQL驱动包
    url: jdbc:mysql://localhost:3306/cloudD801        #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                 #数据库连接池的最小维持连接数
      initial-size: 5                             #初始化链接
      max-toaal: 5                                #最大连接数
      max-wait-millis: 200                        #等待连接获取的最大超时时间






