server:
    port: 80


eureka:
    #server-self-preservation: false //eureka 自我保护机制 关闭 不推荐
    #instance:
     #   hostname: eureka7001.com  #eureka 服务端的实例名称
    client:
        register-with-eureka: false #false 表示不向注册中心注册自己
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #设置Eureka server交互的地址查询服务和注册服务都需要依赖这地址




